import type { Metadata } from "next";

import { Nav } from "@/components/nav";
import { Aside } from "@/components/aside";
import { Login } from "@/components/login";

import "@/style/globals.css";

export const metadata: Metadata = {
  title: "Cove",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen overflow-hidden">
          <Nav />
          <Aside />
          <div className="flex-1 overflow-auto">{children}</div>
          <Login />
        </div>
      </body>
    </html>
  );
}
